### ISSUE TITLE
Read timeout?

### ISSUE THREAD

**Issue by imlazyone** [mapbox/mapbox-sdk-py#109]
Hi, I started testing and everything was fine until I hit this error, I cannot get back any response at all. Meanwhile using the mapboxcli command on the address still works.

Is this related to requests limit or an internal API problem?

```
 $ ve python test.py
Traceback (most recent call last):
  File "test.py", line 202, in <module>
    geocode('5445 2ND AVENUE N, ST PETERSBURG, FL, US')
  File "test.py", line 24, in geocode
    response = geocoder.forward(address)
  File "/Users/one/work/mapbox/.virtualenv/lib/python2.7/site-packages/mapbox/services/geocoding.py", line 43, in forward
    resp = self.session.get(uri, params=params)
  File "/Users/one/work/mapbox/.virtualenv/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/one/work/mapbox/.virtualenv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/one/work/mapbox/.virtualenv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/one/work/mapbox/.virtualenv/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.mapbox.com', port=443): Read timed out. (read timeout=None)
```

**Comment by sgillies** [comment]
I don't see any sign of an API problem. When you hit the rate limit, you're supposed to get a HTTP 429 error (https://www.mapbox.com/developers/api/geocoding/#limits), but since the project's tests don't every hit or test the limit, it's possible that we have a bug here. I'll look into it.

Are you using different tokens for the CLI and your Python program? That could explain why one works and the other does not.

**Comment by imlazyone** [comment]
Hi @sgillies I'm using the same token. The token we have is on an Enterprise plan.

**Comment by imlazyone** [comment]
BTW I believe that on that specific day I did over 30k of requests which may hit the limit already, but now it's been 2 days since last time so I guess the restriction should be cleared already?

FYI here's the result from mapboxcli (using same token):
```
$ ve mapbox geocoding -i '5445 2ND AVENUE N, ST PETERSBURG, FL, US'
```

```
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-rate-limit-interval,x-rate-limit-limit,x-rate-limit-remaining,x-rate-limit-reset
Age: 240524
Cache-Control: max-age=604800
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/vnd.geo+json; charset=utf-8
Date: Fri, 29 Jan 2016 09:13:28 GMT
Etag: "5de7eaa9b126aac55cae028538495a48"
Last-Modified: Fri, 29 Jan 2016 09:13:28 GMT
Transfer-Encoding: chunked
Vary: Accept-Encoding
Via: 1.1 4be0955ad3c1560913d446bc16f27f97.cloudfront.net (CloudFront)
X-Amz-Cf-Id: NyPku-MYE-uGbKJN-wgxR_5Om6ITIN_hiefLPLDnL0uPzOL9T1ZJig==
X-Cache: Hit from cloudfront
X-Powered-By: Express
X-Rate-Limit-Interval: 60
X-Rate-Limit-Limit: 600
X-Rate-Limit-Reset: 1454058867

{"type":"FeatureCollection","query":["5445","2nd","avenue","n","st","petersburg","fl","us"],"features":[{"id":"address.7621468315441160","type":"Feature","text":"2nd Ave N","place_name":"5445 2nd Ave N, Saint Petersburg, Florida 33710, United States","relevance":0.996,"properties":{},"bbox":[-82.74177599999999,27.690918999999997,-82.63443699999999,27.77395999999999],"center":[-82.707647,27.772991],"geometry":{"type":"Point","coordinates":[-82.707647,27.772991]},"address":"5445","context":[{"id":"neighborhood.5945741084793320","text":"East 58th Street"},{"id":"place.43046","text":"Saint Petersburg"},{"id":"postcode.15172179612534380","text":"33710"},{"id":"region.10905096989619270","text":"Florida"},{"id":"country.4150104525","text":"United States","short_code":"us"}]},{"id":"address.10228362368378","type":"Feature","text":"2nd Ave N","place_name":"2nd Ave N, Saint Petersburg, Florida 33701, United States","relevance":0.796,"properties":{},"bbox":[-82.64869999999999,27.77341699999999,-82.63400899999996,27.77354499999999],"center":[-82.636331,27.773535],"geometry":{"type":"Point","coordinates":[-82.636331,27.773535]},"context":[{"id":"neighborhood.2878595007572520","text":"North Downtown"},{"id":"place.43046","text":"Saint Petersburg"},{"id":"postcode.5470344214108200","text":"33701"},{"id":"region.10905096989619270","text":"Florida"},{"id":"country.4150104525","text":"United States","short_code":"us"}]},{"id":"address.50946392147673","type":"Feature","text":"2nd Ave N","place_name":"2nd Ave N, Saint Petersburg, Florida 33713, United States","relevance":0.796,"properties":{},"bbox":[-82.69985199999998,27.772771999999993,-82.65561999999997,27.77296799999999],"center":[-82.6706,27.772841],"geometry":{"type":"Point","coordinates":[-82.6706,27.772841]},"context":[{"id":"neighborhood.11839180213961550","text":"Midtown"},{"id":"place.43046","text":"Saint Petersburg"},{"id":"postcode.5487879428424350","text":"33713"},{"id":"region.10905096989619270","text":"Florida"},{"id":"country.4150104525","text":"United States","short_code":"us"}]},{"id":"address.144256681193716","type":"Feature","text":"2nd Ave N","place_name":"2nd Ave N, Saint Petersburg, Florida 33715, United States","relevance":0.796,"properties":{},"bbox":[-82.72339099999998,27.691103999999992,-82.72337099999999,27.69166299999999],"center":[-82.723391,27.691663],"geometry":{"type":"Point","coordinates":[-82.723391,27.691663]},"context":[{"id":"neighborhood.10599868350004740","text":"Tierra Verde"},{"id":"place.43046","text":"Saint Petersburg"},{"id":"postcode.13438034278451930","text":"33715"},{"id":"region.10905096989619270","text":"Florida"},{"id":"country.4150104525","text":"United States","short_code":"us"}]},{"id":"address.241291371115719","type":"Feature","text":"2nd Ave","place_name":"5445 2nd Ave, Lorida, Florida 33857, United States","relevance":0.62,"properties":{},"bbox":[-81.25212099999997,27.46310699999999,-81.25203199999999,27.470456999999993],"center":[-81.252054,27.46866],"geometry":{"type":"Point","coordinates":[-81.252054,27.46866],"interpolated":true},"address":"5445","context":[{"id":"place.28540","text":"Lorida"},{"id":"postcode.15675078065280090","text":"33857"},{"id":"region.10905096989619270","text":"Florida"},{"id":"country.4150104525","text":"United States","short_code":"us"}]}],"attribution":"NOTICE: © 2016 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained."}
```

I was also curious that I don't see the `x-rate-limit-remaining` header response anywhere as described in your [documentation](https://www.mapbox.com/developers/api/geocoding/#limits).

**Comment by imlazyone** [comment]
I think I figured it out... If you use `monkey.patch_socket()` then I get above timeout error.

I just switched my code to `patch_all()` and it's working now.
```
import gevent.monkey
gevent.monkey.patch_all()
```

**Comment by sgillies** [comment]
@imlazyone thanks for following up. I'm discussing the missing header with the API server developers and will report back here. Briefly, it's being removed during maintenance periods. We'll work on guidance for what that means to users.

**Comment by imlazyone** [comment]
I'm closing the issue it's no longer a problem.

(Would be great if we have feedback on the `x-rate-limit-remaining` header tho)
