### ISSUE TITLE
encoding issue with python 3.6.0

### ISSUE THREAD

**Issue by little-dude** [mapbox/mapbox-sdk-py#169]
Hi,

I'm unable to upload some data files with python 3.6.0. The same files work fine with python 2.7.13.
I attached one of these files (just added a `.txt` extension so that github accepts it)

```
In [1]: from mapbox import Uploader
   ...: service = Uploader()
   ...: mapid = 'STUUUUUUUUUUUFF'
   ...: with open('data/cities_population_2013.geojson', 'r') as src:
   ...:     r=service.upload(src, mapid)
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-f94198119e1d> in <module>()
      6
      7 with open('data/cities_population_2013.geojson', 'r') as src:
----> 8     r=service.upload(src, mapid)

/home/corentih/hackathon/env/lib/python3.6/site-packages/mapbox/services/uploads.py in upload(self, fileobj, tileset, name, patch, callback)
    155         Returns a response object where the json() is a dict with upload metadata
    156         """
--> 157         url = self.stage(fileobj, callback=callback)
    158         return self.create(url, tileset, name=name, patch=patch)

/home/corentih/hackathon/env/lib/python3.6/site-packages/mapbox/services/uploads.py in stage(self, fileobj, creds, callback)
     68
     69         bucket = s3.Bucket(creds['bucket'])
---> 70         bucket.upload_fileobj(fileobj, creds['key'], Callback=callback)
     71
     72         return creds['url']

/home/corentih/hackathon/env/lib/python3.6/site-packages/boto3/s3/inject.py in bucket_upload_fileobj(self, Fileobj, Key, ExtraArgs, Callback, Config)
    467     return self.meta.client.upload_fileobj(
    468         Fileobj=Fileobj, Bucket=self.name, Key=Key, ExtraArgs=ExtraArgs,
--> 469         Callback=Callback, Config=Config)
    470
    471

/home/corentih/hackathon/env/lib/python3.6/site-packages/boto3/s3/inject.py in upload_fileobj(self, Fileobj, Bucket, Key, ExtraArgs, Callback, Config)
    425             fileobj=Fileobj, bucket=Bucket, key=Key,
    426             extra_args=ExtraArgs, subscribers=subscribers)
--> 427         return future.result()
    428
    429

/home/corentih/hackathon/env/lib/python3.6/site-packages/s3transfer/futures.py in result(self)
     71             # however if a KeyboardInterrupt is raised we want want to exit
     72             # out of this and propogate the exception.
---> 73             return self._coordinator.result()
     74         except KeyboardInterrupt as e:
     75             self.cancel()

/home/corentih/hackathon/env/lib/python3.6/site-packages/s3transfer/futures.py in result(self)
    231         # final result.
    232         if self._exception:
--> 233             raise self._exception
    234         return self._result
    235

/home/corentih/hackathon/env/lib/python3.6/site-packages/s3transfer/tasks.py in __call__(self)
    124             # main() method.
    125             if not self._transfer_coordinator.done():
--> 126                 return self._execute_main(kwargs)
    127         except Exception as e:
    128             self._log_and_set_exception(e)

/home/corentih/hackathon/env/lib/python3.6/site-packages/s3transfer/tasks.py in _execute_main(self, kwargs)
    148         )
    149
--> 150         return_value = self._main(**kwargs)
    151         # If the task is the final task, then set the TransferFuture's
    152         # value to the return value from main().

/home/corentih/hackathon/env/lib/python3.6/site-packages/s3transfer/upload.py in _main(self, client, fileobj, bucket, key, extra_args)
    677         """
    678         with fileobj as body:
--> 679             client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
    680
    681

/home/corentih/hackathon/env/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    251                     "%s() only accepts keyword arguments." % py_operation_name)
    252             # The "self" in this scope is referring to the BaseClient.
--> 253             return self._make_api_call(operation_name, kwargs)
    254
    255         _api_call.__name__ = str(py_operation_name)

/home/corentih/hackathon/env/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    522                 operation_name=operation_name),
    523             model=operation_model, params=request_dict,
--> 524             request_signer=self._request_signer, context=request_context)
    525
    526         if event_response is not None:

/home/corentih/hackathon/env/lib/python3.6/site-packages/botocore/hooks.py in emit_until_response(self, event_name, **kwargs)
    240                  is not ``None``, otherwise (``None``, ``None``).
    241         """
--> 242         responses = self._emit(event_name, kwargs, stop_on_response=True)
    243         if responses:
    244             return responses[-1]

/home/corentih/hackathon/env/lib/python3.6/site-packages/botocore/hooks.py in _emit(self, event_name, kwargs, stop_on_response)
    208         for handler in handlers_to_call:
    209             logger.debug('Event %s: calling handler %s', event_name, handler)
--> 210             response = handler(**kwargs)
    211             responses.append((handler, response))
    212             if stop_on_response and response is not None:

/home/corentih/hackathon/env/lib/python3.6/site-packages/botocore/handlers.py in conditionally_calculate_md5(params, context, request_signer, **kwargs)
    165     """Only add a Content-MD5 if the system supports it."""
    166     if MD5_AVAILABLE:
--> 167         calculate_md5(params, **kwargs)
    168
    169

/home/corentih/hackathon/env/lib/python3.6/site-packages/botocore/handlers.py in calculate_md5(params, **kwargs)
    143             binary_md5 = _calculate_md5_from_bytes(body)
    144         else:
--> 145             binary_md5 = _calculate_md5_from_file(body)
    146         base64_md5 = base64.b64encode(binary_md5).decode('ascii')
    147         params['headers']['Content-MD5'] = base64_md5

/home/corentih/hackathon/env/lib/python3.6/site-packages/botocore/handlers.py in _calculate_md5_from_file(fileobj)
    157     md5 = get_md5()
    158     for chunk in iter(lambda: fileobj.read(1024 * 1024), b''):
--> 159         md5.update(chunk)
    160     fileobj.seek(start_position)
    161     return md5.digest()

TypeError: Unicode-objects must be encoded before hashing
```
Now the working version with python 2.7:

```

In [1]: from mapbox import Uploader                                    
                                                                       
In [2]: service = Uploader()                                           
                                                                       
In [3]: mapid = 'FJFEIWOJFWEOIFJOIWFW'                                 
                                                                       
In [4]: with open('data/cities_population_2013.geojson', 'r') as src:  
   ...:     r=service.upload(src, mapid)                               
   ...:                                                                
                                                                       
In [5]: r.status_code                                                  
Out[5]: 201                                                            
```

[cities_population_2013.geojson.txt](https://github.com/mapbox/mapbox-sdk-py/files/887861/cities_population_2013.geojson.txt)

**Comment by perrygeo** [comment]
I can confirm the behavior.  Python 3 makes the distinction between bytes and strings, and the file handle passed to `service.upload` must read an array of bytes. You have to explicitly open the file in binary mode:

On Python 3.6, note the `rb`
```
>>> with open("cities_population_2013.geojson", 'rb') as src:
...     result = service.upload(src, mapid)
...

>>> r.status_code
201
```

This is the preferred method for both python 2 and 3. Let me know if this works for you. It certainly needs to be better documented. I'll add a note to https://github.com/mapbox/mapbox-sdk-py/blob/master/docs/uploads.md#usage

**Comment by little-dude** [comment]
thanks, it makes sense now :)
it does work when opening the file in binary mode.

**Comment by jliebrand** [comment]
I'm seeing a similar problem on our build machine (python 2.7) using mapbox-cli. Is this related?

```
  File "/usr/local/lib/python2.7/dist-packages/mapboxcli/scripts/uploads.py", line 71, in upload
    callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/mapbox/services/uploads.py", line 157, in upload
    url = self.stage(fileobj, callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/mapbox/services/uploads.py", line 70, in stage
    bucket.upload_fileobj(fileobj, creds['key'], Callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 469, in bucket_upload_fileobj
    Callback=Callback, Config=Config)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 427, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2588' in position 31: ordinal not in range(128)
Exited with code 1

```

Should I raise this on mapbox-cli repo?

**Comment by perrygeo** [comment]
@jliebrand It's not related to this issue but looks like a bug indeed. Could you create a ticket in mapbox-cli-py, if possible including the data and the command used to hit that error? Thanks!

**Comment by jliebrand** [comment]
repro should be easy, just use our docker image savvynavvy/buildpack

I've raised a bug here:
https://github.com/mapbox/mapbox-cli-py/issues/97

**Comment by sheub** [comment]
Hi, 
The [online doc](https://www.mapbox.com/api-documentation/?language=Python#create-an-upload) should be eventually corrected

> with open('data.geojson', 'r') as src:
    # Acquisition of credentials, staging of data, and upload
    # finalization is done by a single method in the Python SDK.
    upload_resp = service.upload(src, '{username}.data')
